### ISSUE TITLE
ui界面监控的后端服务改成fastapi吧

### ISSUE THREAD

**Issue by yioyoiyioys222** [qyzhg/atomic-bomb-engine-py#51]
![image](https://github.com/qyzhg/atomic-bomb-engine-py/assets/50391716/fb725290-ac01-44e9-8c78-ad18e65c4e7f)

**Comment by qyzhg** [comment]
本身这个ui界面就是一个demo,给大家提供一个做平台的思路，不参与直接发压，引入fastapi后，整个项目就会为了一个边缘功能变的十分臃肿
