### ISSUE TITLE
增加对阶梯加压的使用文档说明

### ISSUE THREAD

**Issue by yioyoiyioys222** [qyzhg/atomic-bomb-engine-py#61]
@qyzhg 嗨，我看到0.15.0版本增加对阶梯加压支持，是否可以增加对这块的使用文档说明

**Comment by qyzhg** [comment]
文档中0.15发布的时候已经更新了step_option的简单说明，这块功能比较简单，就两个参数，一个是步长，就是每次阶梯增加多少个压力，另一个是间隔时间，就是每一步加压后等待多久进行第二步加压
